export const API_ERROR = 'EVENT/API_ERROR_RECEIVED';
export const WEATHER_DATA_RECEIVED = 'EVENT/WEATHER_DATA_RECEIVED';


export const SWITCH_CHART = 'EVENT/SWITCH_CHART';
export const SWITCH_NOWWHAT = 'EVENT/SWITCH_NOWWHAT';

export const METRICS_DATA_RECEIVED = "EVENT/METRICS_DATA_RECEIVED";
export const METRIC_API_CALL_FAIL = "EVENT/METRIC_API_CALL_FAIL";

export const METRICS_MEASUREMENTS_RECEIVED = "EVENT/METRICS_MEASUREMENTS_RECEIVED";
export const NEW_MEASUREMENTS_RECEIVED = "EVENT/NEW_MEASUREMENT_DATA_RECEIVED";
export const NEW_MEASUREMENTS_API_CALL_FAIL = "EVENT/NEW_MEASUREMENTS_API_CALL_FAIL";
export const MULTIPLE_MEASUREMENTS_API_CALL_FAIL = 'EVENT/MULTIPLE_MEASUREMENTS_API_CALL_FAIL'