export const API_ERROR = 'EVENT/API_ERROR_RECEIVED';
export const WEATHER_DATA_RECEIVED = 'EVENT/WEATHER_DATA_RECEIVED';


export const SWITCH_WEATHER = 'EVENT/SWITCH_WEATHER';
export const SWITCH_NOWWHAT = 'EVENT/SWITCH_NOWWHAT';

export const METRICS_DATA_RECEIVED = "EVENT/METRICS_DATA_RECEIVED";
export const METRIC_API_CALL_FAIL = "EVENT/METRIC_API_CALL_FAIL";